global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
scrape_configs:
- job_name: java-tron
  honor_timestamps: true
  scrape_interval: 3s
  scrape_timeout: 2s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - fullnode:9527
    labels:
      group: TRON
      instance: LITENODE